version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rails_playground
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: ap-northeast-1
      BUCKET_NAME: rails-playground # init.sh で指定したバケット名と同じ
    depends_on:
      - db
      - localstack # docker compose up 時に localstack も起動する

  localstack:
    image: localstack/localstack:3.6.0
    ports:
      - "4566:4566"
    environment:
      AWS_ACCESS_KEY_ID: test # S3_SKIP_SIGNATURE_VALIDATION を 0 に設定することで test が固定値に
      AWS_SECRET_ACCESS_KEY: test # 上に同じ
      AWS_DEFAULT_REGION: ap-northeast-1
      SERVICES: s3 # s3 のみ利用
      S3_SKIP_SIGNATURE_VALIDATION: 0 # 正しい署名付き URL でなければファイルにアクセスできないようする
      DISABLE_CUSTOM_CORS_S3: 1 # S3 による CORS オーバーライドを無効にする
    volumes:
      - localstack_volume:/etc/localstack
      - ./init.sh:/etc/localstack/init.sh

volumes:
  db_data:
  localstack_volume:
